tourMatch/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

tourMatch/tourMatch/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('account/', include('account.urls', namespace='account')),
    path('tournament/', include('tournament.urls', namespace='tournament'))
    
    # path('test/', views.TestPage.as_view(), name='test'),
    # path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    # path('posts/', include("posts.urls", namespace="posts")),
    # path('groups/', include("groups.urls", namespace="groups"))
]

tourMatch/tournament/urls.py
from django.urls import path
from . import views, forms

app_name = 'tournament'

urlpatterns = [
    path('by/<username>/', views.tournamnet_list, name="list"),
    path('by/<username>/<int:pk>', views.tournament_detail, name="detail"),
    path('simulate/', views.create_tournament, name="simulate"),
]

tourMatch/account/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User, auth.models.PermissionsMixin):
    def __str__(self):
        return self.username

tourMatch/tournament/models.py
from django.db import models
from django.contrib.auth.models import User
import json

# Create your models here.
class Tournament (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tournament_name = models.CharField(max_length=100)
    participants = models.DecimalField(max_digits=2, decimal_places=0)
    result = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def set_result(self, result):
        self.result = json.dumps(result)

    def get_result(self):
        return json.loads(self.result)

tourMatch/account/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

        def __init__(self, *args , **kwargs):
            super().__init__(*args, **kwargs)
            for field in self.fields:
                self.fields[field].widget.attrs['class'] = 'form-control'

            self.fields['username'].label = 'Display Name'
            self.fields['email'].label = 'Email Address'

tourMatch/tournament/forms.py
from django.contrib.auth import get_user_model
from django import forms
from . import models


class TournamentForm(forms.ModelForm):
    choice = [(1, "16"),(2, "32"),(3, "64")]
    participants_choice = forms.ChoiceField(choices=choice, widget=forms.Select(attrs={'class': 'form-control mt-2', 'style': 'width: 60px;'}))
    random = forms.BooleanField(label="Randomize Players", required=False, widget=forms.CheckboxInput(attrs={'class': 'largerCheck'}))
    class Meta:
        model = models.Tournament
        fields = ('tournament_name', 'random', 'participants_choice')

tourMatch/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms

# Create your views here.
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('account:login')
    template_name = 'accounts/signup.html'

tourMatch/tourMatch/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

tourMatch/tournament/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import TournamentForm
import random

# Create your views here.
@login_required
def tournament_detail (request):
    return 

@login_required
def tournamnet_list(request):
    return


def create_tournament(request):
    form = TournamentForm(request.POST)
    if form.is_valid():
        participants_data = form.cleaned_data['participants_choice']
        tournament_name = form.cleaned_data['tournament_name']
        random = form.cleaned_data['random']
        match_count = 1
        number_match = 0
        stage = list("ABCDEFGHIJKLMNOP")
        if participants_data == '1':
            participants = list(range(1, 17))
            if random:
                participants = randomize(participants)
            else:
                participants = returnList(participants)
            return render(request, 'tournament/create_tournament_16.html', {'participants': participants, 'number_match': number_match, 'match_count': match_count, 't_name': tournament_name})
        elif participants_data == '2':
            participants = list(range(1, 33))
            if random:
                participants = randomize(participants)
            else:
                participants = returnList(participants)
            return render(request, 'tournament/create_tournament_32.html', {'participants': participants, 'number_match': number_match, 'match_count': match_count, 't_name': tournament_name})
        elif participants_data == '3':
            participants = list(range(1, 65))
            if random:
                participants = randomize(participants)
            else:
                participants = returnList(participants)
            return render(request, 'tournament/create_tournament_64.html', {'participants': participants, 'stage': stage, 'number_match': number_match, 'match_count': match_count, 't_name': tournament_name})
        else:
            return render(request, 'tournament/fail.html')
    else:
        form = TournamentForm
    return render(request, 'tournament/set_tournament.html', {'form': form})

def randomize(list):
    randomized = []
    while(len(list)>0):
        sublist = []
        for i in range(0, 4):
            sublist.append(list.pop(random.randint(0, len(list)-1)))
            if i == 3:
                randomized.append(sublist)
    return randomized

def returnList(list):
    non_random = []
    chunk_size = 4
    while(len(list)>0):
        chunk, list = list[:chunk_size], list[chunk_size:]
        non_random.append(chunk)

    return non_random

tourMatch/account/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Login</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark" value="Login">
  </form>
</div>

{% endblock %}

tourMatch/account/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-dark" value="Sign Up">
  </form>
</div>

{% endblock %}

tourMatch/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tourMatch</title>

    <link href="{% static 'tourMatch/images/TourMatch-logos.jpeg' %}" rel="shortcut icon" type="image/x-icon">

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!-- master css -->
    <link rel="stylesheet" href="{% static 'tourMatch/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'tourMatch/css/master.css' %}">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">
                <img class="logo" src="{% static 'tourMatch/images/TourMatch-logos.jpeg'%}" alt="tourMatch-logo" width="70px">
            </a>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'tournament:simulate' %}">Tournament</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'account:logout' %}">Log Out</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'tournament:list' username=user.username %}">History</a></li>
                {% else %}
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'tournament:simulate' %}">Tournament</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'account:login' %}">Log In</a></li>
                <li><a class="nav-item nav-link btn btn-simple" href="{% url 'account:signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}
        
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src="{% static 'tourMatch/js/master.js'%}"></script>
</body>
</html>

tourMatch/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to TourMatch!</h1>
    <p>TourMatch is a website for tournament simulation.</p>
{% endblock %}

tourMatch/templates/includes/alerts.html
{% if messages %}
<div id="messages" class="container">
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}

tourMatch/templates/tour_save.html
<div class="save">
    <button>Save Tournament</button>
</div>  

tourMatch/tournament/templates/tournament/create_tournament_16.html
{% extends 'base.html' %}
{% load my_tags %}

{% block content %}
<div class="container tournament-chart">
    <div id="contents">
        <div class="bracket_overflow">
            <div class="title">
                <h1>{{t_name}}</h1>
            </div>
            <div class="match_list_outer" id="bracket">
                <div class="round_set_outer">
                    <div class="round_set">
                        <p class="screen">Round of 16</p>
                    </div>
                    <div class="round_set">
                        <p class="screen">Quarterfinals</p>
                    </div>
                    <div class="round_set">
                        <p class="screen">Semifinals</p>
                    </div>
                    <div class="round_set">
                        <p class="screen">Final</p>
                    </div>
                    <div class="round_set">
                        <p class="screen">Winner</p>
                    </div>
                </div>
                <div id="players">
                    <div class="match_01 round_group">
                        {% for sublist in participants %}
                        <div class="match_g01">
                            {% with match_count=forloop.counter|add:"-1"|mul:"2"|add:"1"|sum_digits %}
                            <div class="match_list number{{match_count}}">
                                <p class="bracket_num">Match #<em>{{match_count}}</em></p>
                                <div class="box_s">
                                    <div class="match_list_cont01 l01"><span>{{forloop.counter|add:"-1"|mul:"4"|add:"1"|sum_digits}}</span>
                                        <div><p>Player{{sublist.0}}</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span>{{forloop.counter|add:"-1"|mul:"4"|add:"2"|sum_digits}}</span>
                                        <div><p>Player{{sublist.1}}</p></div>
                                    </div>
                                    
                                </div>
                            </div>
                            {% endwith %}                                   
                            {% with match_count=forloop.counter|add:"-1"|mul:"2"|add:"2"|sum_digits %}
                            <div class="match_list bottom01 number{{match_count}}">
                                <p class="bracket_num">Match #<em>{{match_count}}</em></p>
                                <div class="box_s">
                                    <div class="match_list_cont01 l01"><span>{{forloop.counter|add:"-1"|mul:"4"|add:"3"|sum_digits}}</span>
                                        <div><p>Player{{sublist.2}}</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span>{{forloop.counter|add:"-1"|mul:"4"|add:"4"|sum_digits}}</span>
                                        <div><p>Player{{sublist.3}}</p></div>
                                    </div>
                                </div>
                            </div>
                            {% endwith %}
                        </div>
                        {% endfor %}
                    </div>                 
                    <div class="match_02 round_group">
                        {% with number_match=participants|length|div:"2"|times %}
                        {% for number in number_match %}
                        <div class="match_g01">
                            <div class="match_list">
                                <p class="bracket_num">Match #<em>{{number|add:"-1"|mul:"2"|add:"1"|sum_digits}}</em></p>
                                <div class="box_s">                                    
                                    <div class="match_list_cont01 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="match_list bottom01">
                                <p class="bracket_num">Match #<em>{{number|add:"-1"|mul:"2"|add:"2"|sum_digits}}</em></p>
                                <div class="box_s">
                                    <div class="match_list_cont01 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                    <div class="match_03 round_group">
                        {% with number_match=participants|length|div:"4"|times %}
                        {% for number in number_match %}
                        <div class="match_g01">
                            <div class="match_list">
                                <p class="bracket_num">Match #<em>{{number|add:"-1"|mul:"2"|add:"1"|sum_digits}}</em></p>
                                <div class="box_s">                                    
                                    <div class="match_list_cont01 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="match_list bottom01">
                                <p class="bracket_num">Match #<em>{{number|add:"-1"|mul:"2"|add:"2"|sum_digits}}</em></p>
                                <div class="box_s">
                                    <div class="match_list_cont01 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                </div>
                            </div>                            
                        </div>
                        {% endfor %}
                        {% endwith %}                        
                    </div>
                    <div class="match_04 round_group last_match">
                        <div class="match_g01">
                            <div class="match_list">
                                <p class="bracket_num">Match #<em>1</em></p>
                                <div class="box_s">                                    
                                    <div class="match_list_cont01 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>
                                    
                                    <div class="match_list_cont02 l01"><span></span>
                                        <div><p>Player</p></div>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="last_match champion_box round_group">
                        <div class="match_list">
                            <p class="txt bracket_num">Winner</p>
                            <div class="player">
                                <div class="winner"><p>Player</p></div>
                            </div>
                        </div>
                    </div>         
                    </div>
            </div>

        </div>
    </div>
</div>
{% include 'tour_save.html' %}
{% endblock %}

tourMatch/tournament/templates/tournament/fail.html
{% extends 'base.html' %}
{% block content %}
<h1>Oops. Something went wrong</h1>
{% endblock %}

tourMatch/tournament/templates/tournament/set_tournament.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    <div class="col-md-6 form-control py-3">
      <label for="">Tournament Name</label>
      <input type="text" name="tournament_name" class="form-control mx-auto my-auto" style="box-sizing: content-box; width: 98%;">
    </div>
    <div class="col-md-6 form-control py-3">
      <label for="">Random</label>
      <input type="checkbox" name="random">
    </div>
    <div class="col-md-6 form-control py-3">
      <label for="">Participants_choice</label>
      <div class="">
        {{form.participants_choice}}
      </div>
    </div>
    <input type="submit" value="Create Tournament" class="btn btn-primary"/>
  </form>
{% endblock %}